### ISSUE TITLE
How can i get number of seconds since Epoch

### ISSUE THREAD

**Issue by tkralj** [Zanduino/MCP7940#59]
Hello , i want to create OTP token using Arduino TOTP Library. I dont know how to get number of seconds since Epoch using your library. Can you help please ?

**Comment by SV-Zanshin** [comment]
This would be done in the DateTime class using "unixtime" - that would be the number of seconds since 01.01.1970 00:00:00.

See the library wiki page at  [DateTimeClass](https://github.com/Zanduino/MCP7940/wiki/DateTimeClass)

Does that answer your question?

**Comment by tkralj** [comment]
Hello, yes, that's it. Thank you !

**Comment by SV-Zanshin** [comment]
Excellent, glad to be able to help.
